-- 매출액, 저자 ID, 저자명, 카테고리, 매출액 --
SELECT A.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) as TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
-- 2022년 1월 판매 --
WHERE S.SALES_DATE LIKE '2022-01%'
-- 저자, 카테고리 그룹 --
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
-- 저자 ID 오름차, 카테고리 내림차 --
ORDER BY AUTHOR_ID, CATEGORY DESC