-- 년, 월, 성별, 회원수 --
SELECT YEAR(S.SALES_DATE) as YEAR,
    MONTH(S.SALES_DATE) as MONTH,
    U.GENDER as GENDER,
    COUNT(DISTINCT S.USER_ID) as USERS
FROM ONLINE_SALE S
-- 조인 --
JOIN USER_INFO U
ON S.USER_ID = U.USER_ID
-- 성별 정보 없는 경우 제외 --
WHERE U.GENDER IS NOT NULL
-- 그룹 --
GROUP BY YEAR, MONTH, GENDER
-- 년, 월, 성별 오름차 --
ORDER BY YEAR, MONTH, GENDER