-- 월, ID, 대여 횟수 조회 --
SELECT MONTH(car.START_DATE) as MONTH,
    car.CAR_ID,
    COUNT(car.HISTORY_ID) as RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as car
JOIN (SELECT CAR_ID, COUNT(*) as TOTAL_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
        AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID) as rec
ON car.CAR_ID = rec.CAR_ID
-- 2022-08 ~ 2022-10 대여 횟수 5회 이상 --
WHERE TOTAL_COUNT >= 5
    AND (START_DATE >= '2022-08-01'
        AND START_DATE < '2022-11-01')
GROUP BY CAR_ID, MONTH
-- 월 오름차, ID 내림차 --
ORDER BY MONTH, CAR_ID DESC