-- 연도, 크기 편차, 개체ID --
SELECT YEAR(DIFFERENTIATION_DATE) as YEAR,
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))
     - SIZE_OF_COLONY
    ) as YEAR_DEV,
    ID
FROM ECOLI_DATA
-- 연도 오름차, 크기 편차 --
ORDER BY YEAR, YEAR_DEV