-- 맛 조회 --
SELECT HALF.FLAVOR
FROM FIRST_HALF as HALF
JOIN ICECREAM_INFO as INFO
ON HALF.FLAVOR = INFO.FLAVOR
-- 총주문량이 3,000 보다 높고, 주 성분이 과일 --
WHERE HALF.TOTAL_ORDER >= 3000
    AND INFO.INGREDIENT_TYPE = 'fruit_based'
-- 총 주문량 큰 순서대로 --
ORDER BY TOTAL_ORDER DESC