-- ID, 이름, 길이 --
SELECT F.ID as ID, N.FISH_NAME as FISH_NAME, F.LENGTH as LENGTH
FROM FISH_INFO as F
JOIN FISH_NAME_INFO as N
ON F.FISH_TYPE = N.FISH_TYPE
-- 서브쿼리 --
WHERE F.FISH_TYPE IN
    (SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
    )
-- ID 오름차 --
ORDER BY ID