-- 성분, 총주문량 조회 --
SELECT I.INGREDIENT_TYPE,
    SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM FIRST_HALF F
-- 조인 --
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
-- 그룹: 성분 타입 --
GROUP BY I.INGREDIENT_TYPE
-- 총주문량 작은순 --
ORDER BY TOTAL_ORDER