-- 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 내용, 작성일 --
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as B
JOIN USED_GOODS_REPLY as R
ON B.BOARD_ID = R.BOARD_ID
-- 2022년 10월에 작성된 게시글 --
WHERE B.CREATED_DATE LIKE '2022-10%'
-- 작서일 오름차, 제목 오름차 -- 
ORDER BY R.CREATED_DATE, B.TITLE